title: [Macy Tham]
description: Current Masters in Engineering Management and Leadership graduate student with a background in Chemical Engineering and a focus on Energy Transition and Lean Systems
theme: jekyll-theme-minimal
